proxy_cache_path /tmp/cdn_cache levels=1:2 keys_zone=cdn_cache:10m max_size=4g inactive=60m use_temp_path=off;

server {
    listen 80;
    server_name cdn.local;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location ~* \.mp4$ {
        proxy_pass http://192.168.88.253:8081;



        proxy_ignore_headers Cache-Control Expires Set-Cookie;

        proxy_cache cdn_cache;
        proxy_cache_valid 200 10m;
        proxy_cache_use_stale error timeout updating;

        add_header X-Cache $upstream_cache_status;
        add_header X-Servidor "cdn";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_max_temp_file_size 4096m;
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}
