services:
  origem:
    image: nginx:alpine
    container_name: origem
    volumes:
      - ./origem/index.html:/usr/share/nginx/html/index.html
      - ./origem/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      cdn_network:
        ipv4_address: 172.20.0.10

  cdn:
    image: nginx:alpine
    container_name: cdn
    ports:
      - "8080:80"
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - origem
    networks:
      cdn_network:
        ipv4_address: 172.20.0.20

networks:
  cdn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
